sudo: required  
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
python:
    - "3.6"
services: docker
script:
    - docker-compose build
before_deploy:
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    script:
        docker tag docker-to-aws-with-dotnet:latest leoaidar/docker-to-aws-with-dotnet:latest;
        docker push leoaidar/docker-to-aws-with-dotnet; 
    on:
        branch: master            
after_success:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - python3 -V
    - pip3 -V
    - pip3 uninstall wheel
    - pip3 install wheel
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - aws --version
    - export PATH=$PATH:HOME/.local/bin    
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 997605063764.dkr.ecr.us-east-2.amazonaws.com
    - docker tag docker-to-aws-with-dotnet:latest $IMAGE_REPO_URL:latest
    - docker push $IMAGE_REPO_URL:latest
notifications:
    email: false