version: '3.4'

services:
  docker-to-aws-with-dotnet:
    image: docker-to-aws-with-dotnet:dev
    container_name: DockerToAWSWithDotNet
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DockerToAWSWithDotNet"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_docker-to-aws-with-dotnet$
    volumes:
      - D:\rep\ls\Microservices\Estudos\DockerToAWSWithDotNet\DockerToAWSWithDotNet:/app
      - D:\rep\ls\Microservices\Estudos\DockerToAWSWithDotNet:/src
      - C:\Users\leonardo.silva\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_docker-to-aws-with-dotnet$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_docker-to-aws-with-dotnet$ \"/app/bin/Debug/netcoreapp2.0/DockerToAWSWithDotNet.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true